const resList = [
  {
    info: {
      id: "483519",
      name: "Cafe tato - Panaji",
      cloudinaryImageId: "s9zor4hjliueeofgunmv",
      locality: "Gera Imperim",
      areaName: "Panaji",
      costForTwo: "₹500 for two",
      cuisines: ["Goan", "Indian", "South Indian", "Snacks"],
      avgRating: 4.3,
      veg: true,
      feeDetails: {
        restaurantId: "483519",
        fees: [],
        totalFee: 2400,
      },
      parentId: "290430",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "454489",
      name: "Cafe Ashwini",
      cloudinaryImageId: "l6msxjs2twuxw6licmwm",
      locality: "Opp Pwd",
      areaName: "Panaji",
      costForTwo: "₹250 for two",
      cuisines: ["Indian", "Snacks", "Beverages"],
      avgRating: 4,
      veg: true,
      feeDetails: {
        restaurantId: "454489",
        fees: [],
        totalFee: 2900,
      },
      parentId: "273354",
      avgRatingString: "4.0",
      totalRatingsString: "500+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "292209",
      name: "Sheetal Pure Veg Restaurant- St INEZ",
      cloudinaryImageId: "kk8v3vb4vrvrowf85ouo",
      locality: "st Inez Tiswadi",
      areaName: "Panaji",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "South Indian"],
      avgRating: 4.2,
      veg: true,
      feeDetails: {
        restaurantId: "292209",
        fees: [],
        totalFee: 2400,
      },
      parentId: "182657",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "231324",
      name: "Cafe Mira",
      cloudinaryImageId: "vnuhcbs3wkk2rpbjzn2n",
      areaName: "Panaji",
      costForTwo: "₹180 for two",
      cuisines: ["South Indian", "Gujarati", "Snacks"],
      avgRating: 4.3,
      feeDetails: {
        restaurantId: "231324",
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 2900,
          },
          {
            name: "BASE_TIME",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
          },
        ],
        totalFee: 2900,
      },
      parentId: "53676",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "451111",
      name: "Cafe Bhonsle",
      cloudinaryImageId: "vwpfvay3c0nejv42im1i",
      locality: "Near Cine National",
      areaName: "Panaji",
      costForTwo: "₹500 for two",
      cuisines: ["Beverages", "Snacks", "North Indian", "Chinese"],
      avgRating: 4.2,
      veg: true,
      feeDetails: {
        restaurantId: "451111",
        fees: [],
        totalFee: 2400,
      },
      parentId: "271246",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "291780",
      name: "Sheetal Udupi Pure Veg",
      cloudinaryImageId: "cg7pj3komiwtkgvm0npb",
      locality: "Mg Road",
      areaName: "Panaji",
      costForTwo: "₹200 for two",
      cuisines: ["Indian", "Chinese", "South Indian"],
      avgRating: 4.2,
      veg: true,
      feeDetails: {
        restaurantId: "291780",
        fees: [],
        totalFee: 2400,
      },
      parentId: "182665",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "122680",
      name: "Sanyog",
      cloudinaryImageId: "vupshnuelrlbs3lekfs9",
      locality: "Dr Pissurlekar Road",
      areaName: "Panaji",
      costForTwo: "₹900 for two",
      cuisines: ["Indian"],
      avgRating: 4.4,
      veg: true,
      feeDetails: {
        restaurantId: "122680",
        fees: [],
        totalFee: 2400,
      },
      parentId: "177833",
      avgRatingString: "4.4",
      totalRatingsString: "5K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "279633",
      name: "Udupi Darshini ",
      cloudinaryImageId: "xtk52yn2ql3aypttxkza",
      locality: "Opp Navtara Hotel",
      areaName: "Porvorim",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "Snacks", "Indian"],
      avgRating: 4.1,
      veg: true,
      feeDetails: {
        restaurantId: "279633",
        fees: [],
        totalFee: 5400,
      },
      parentId: "219005",
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {},
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "283089",
      name: "Navaratna Udupi Pure Veg (NR)",
      cloudinaryImageId: "rnenjljwcwh240sjif9z",
      locality: "Alto Betim",
      areaName: "Porvorim",
      costForTwo: "₹500 for two",
      cuisines: ["South Indian", "Indian", "Goan", "Chinese"],
      avgRating: 4.2,
      feeDetails: {
        restaurantId: "283089",
        fees: [],
        totalFee: 4400,
      },
      parentId: "393156",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {},
      availability: {},
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {},
      aggregatedDiscountInfoV3: {},
      orderabilityCommunication: {},
      differentiatedUi: {},
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: {
      link: "https://www.swiggy.com/restaurants/navaratna-udupi-pure-veg-nr-alto-betim-porvorim-central-goa-283089",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];

export default resList;
